---
- hosts: default
  sudo: yes

  tasks:
    - name: set timezone
      copy: src=files/timezone
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
      notify:
        - update timezone

    - name: install ntp
      apt: pkg=ntp state=latest

    - name: make sure ntp is running
      service: name=ntp state=running enabled=yes

    - name: install golang
      shell: curl -L http://golang.org/dl/go1.3.linux-amd64.tar.gz | tar -zxC /usr/local
             creates=/usr/local/go

    - name: add golang to path
      copy: src=files/golang.sh
            dest=/etc/profile.d/golang.sh
            owner=root
            group=root
            mode=0644

    - name: install packages
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - git
        - make
        - mercurial

    - name: install bash_profile
      copy: src=files/dot.bash_profile
            dest=/home/vagrant/.bash_profile
            owner=vagrant
            group=vagrant
            mode=0644

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend=noninteractive tzdata